# Run artisan command
alias a="php artisan"

alias as="php artisan serve"
alias rl="php artisan route:list --except-vendor"
alias controller="php artisan make:controller"
alias model="php artisan make:model"
alias migrate="php artisan migrate"
alias migration="php artisan make:migration"
alias mf="php artisan migrate:fresh"
alias mfs="php artisan migrate:fresh --seed"
alias refresh="php artisan migrate:refresh"
alias rollback="php artisan migrate:rollback"
alias key="php artisan key:generate"
alias ks="php artisan key:generate --show"
alias cc="php artisan cache:clear"
alias cr="php artisan route:clear"
alias cconf="php artisan config:clear"
alias cview="php artisan view:clear"
alias opt="php artisan optimize"
alias optclear="php artisan optimize:clear"
alias init="git init"
alias add="git add ."
alias commit="git commit -m"
alias gpo="git push origin"
alias gp="git push"
alias gs="git status"
alias gpull="git pull"
alias gf="git fetch"
alias start="sudo /opt/lampp/lampp start"
alias restart="sudo /opt/lampp/lampp restart"
alias stop="sudo /opt/lampp/lampp stop"
alias vhost="sudo gedit /opt/lampp/etc/extra/httpd-vhosts.conf"
alias etchost="sudo gedit /etc/hosts"
alias permit="sudo chmod -R 777"
alias autocrlf="git config core.autocrlf true"
alias sphp="sudo update-alternatives --config php"
alias pv="php --version"
alias open="xdg-open"
alias stopnginx="sudo service nginx stop"
alias ..="cd .."
alias pint="./vendor/bin/pint"
alias pivot="a make:migration:pivot"

# commit changes with "wip" message
function wip() {
    git add .
    git commit -m "wip"
    git push
}